// vue/custom-toolbar/src/App.vue
<template>
    <div>
        <div class="flex-container">
            <label class="switchLabel" for="checked">Standalone PDF Viewer</label>
            <div class="e-message render-mode-info">
                <span class="e-msg-icon render-mode-info-icon" title="Turn OFF to render the PDF Viewer as server-backed"></span>
            </div>
            <div>
                <ejs-switch cssClass="buttonSwitch" id="checked" :change="change" :checked="true"></ejs-switch>
            </div>
        </div>
        
        <ejs-toolbar id="customToolbar" ref="toolbar">
            <e-items>
                <e-item prefixIcon='e-pv-open-document-icon' tooltipText='Open' :click="openClicked"></e-item>
                <e-item prefixIcon='e-pv-previous-page-navigation-icon' id="previousPage" tooltipText='Previous Page'
                    align='Center' :click="previousClicked"></e-item>
                <e-item prefixIcon='e-pv-next-page-navigation-icon' id="nextPage" tooltipText='Next Page' align='Center'
                    :click="nextClicked"></e-item>
                <e-item :template="'pageNoTemplate'" tooltipText='Page Number' align='Center'>
                    <template v-slot:pageNoTemplate>
                        <div class=""><input type="text" class="e-input-group e-pv-current-page-number" id="currentPage" />
                        </div>
                    </template>
                </e-item>
                <e-item :template="'pageTextTemplate'" tooltipText='Page Number' align='Center'>
                    <template v-slot:pageTextTemplate>
                        <div class=""><span class="e-pv-total-page-number" id="totalPage">of 0</span></div>
                    </template>
                </e-item>
                <e-item prefixIcon='e-pv-print-document-icon' tooltipText='Print' align='Right'
                    :click="printClicked"></e-item>
                <e-item prefixIcon='e-pv-download-document-icon' tooltipText='Download' align='Right'
                    :click="downloadClicked"></e-item>
            </e-items>
        </ejs-toolbar>
        <ejs-toolbar id="magnificationToolbar">
            <e-items>
                <e-item prefixIcon='e-pv-fit-page-icon' id="fitPage" tooltipText='Fit to page'
                    :click="pageFitClicked"></e-item>
                <e-item prefixIcon='e-pv-zoom-in-icon' id="zoomIn" tooltipText='Zoom in' :click="zoomInClicked"></e-item>
                <e-item prefixIcon='e-pv-zoom-out-icon' id="zoomOut" tooltipText='Zoom out'
                    :click="zoomOutClicked"></e-item>
            </e-items>
        </ejs-toolbar>

        <input type="file" id="fileUpload" accept=".pdf" style="display:block;visibility:hidden;width:0;height:0;" />

        <div class="control-section">
            <ejs-pdfviewer 
                id="pdfviewer" 
                ref="pdfviewer" 
                :pageChange="pageChange" 
                :documentLoad="documentLoad" 
                :documentPath="documentPath" 
                :enableToolbar="enableToolbar" 
                :enableNavigationToolbar="enableNavigationToolbar">
            </ejs-pdfviewer>
        </div>


    </div>
</template>

<style>
/* custom code start*/
#pdfviewer {
    height: 640px;
}

#magnificationToolbar {
    background: transparent;
    height: auto;
    min-height: 56px;
    width: auto;
    border: none;
    position: absolute;
    z-index: 900;
    top: calc(100% - 140px);
    left: calc(100% - 150px);
    transform: rotate(90deg);
}

div#magnificationToolbar.e-toolbar .e-toolbar-items {
    background: transparent;
    padding: 2px 3px 2px 2px;
}

#magnificationToolbar.e-toolbar .e-tbar-btn {
    border-radius: 50%;
    min-height: 30px;
    min-width: 30px;
    border: 1px solid #c8c8c8;
}

#customToolbar {
    top: 20px;
    z-index: 900;
}

.e-bookmark-popup {
    height: 300px;
    max-width: 300px;
}

.e-text-search-popup {
    height: 104px;
    max-width: 348px;
}

.e-custom-search-input {
    width: 234px;
}

.e-text-search-popup .e-footer-content,
.e-bookmark-popup .e-footer-content {
    padding: 0;
    height: 0;
}

.search-button,
.search-button:disabled,
.search-button:focus,
.search-button:hover {
    background: transparent;
    box-shadow: none;
}

#popup .e-dlg-content {
    padding-left: 0;
    padding-bottom: 0;
}

.e-pv-bookmarks {
    min-width: 234px;
}

.e-pv-current-page-number {
    width: 46px;
    height: 28px;
    text-align: center;
}

.material .e-pv-current-page-number {
    border-width: 1px;
}

.e-pv-open-document-icon::before {
    content: '\\e91c';
    font-family: "e-pdfviewer-icons";
}

.e-pv-download-document-icon::before {
    content: '\\e914';
    font-family: "e-pdfviewer-icons";
}

.e-pv-print-document-icon::before {
    content: '\\e917';
    font-family: "e-pdfviewer-icons";
}

.e-pv-previous-page-navigation-icon::before {
    content: '\\e910';
    font-family: "e-pdfviewer-icons";
}

.e-pv-next-page-navigation-icon::before {
    content: '\\e911';
    font-family: "e-pdfviewer-icons";
}

.e-pv-zoom-out-icon::before {
    content: '\\e912';
    font-family: "e-pdfviewer-icons";
}

.e-pv-zoom-in-icon::before {
    content: '\\e91d';
    font-family: "e-pdfviewer-icons";
}

.e-pv-fit-page-icon::before {
    content: '\\e91b';
    font-family: "e-pdfviewer-icons";
}

.e-btn-icon.e-pv-zoom-out-icon.e-icons {
    transform: rotate(90deg);
}

@font-face {
    font-family: "e-pdfviewer-icons";
    font-style: normal;
    font-weight: normal;
    src: url(data:application/x-font-ttf;charset=utf-8;base64,AAEAAAAKAIAAAwAgT1MvMj8wS0QAAAEoAAAAVmNtYXDSeNLMAAABuAAAAFZnbHlmok0NtwAAAjAAAAPkaGVhZBN3pEcAAADQAAAANmhoZWEHrwNhAAAArAAAACRobXR4NsgAAAAAAYAAAAA4bG9jYQdkBmQAAAIQAAAAHm1heHABHAAwAAABCAAAACBuYW1lD0oZXgAABhQAAALBcG9zdFG4mE4AAAjYAAAAyAABAAADUv9qAFoEAAAA/+gEAAABAAAAAAAAAAAAAAAAAAAADgABAAAAAQAAxsly1F8PPPUACwPoAAAAANgsr7EAAAAA2CyvsQAAAAAEAAQAAAAACAACAAAAAAAAAAEAAAAOACQABAAAAAAAAgAAAAoACgAAAP8AAAAAAAAAAQPqAZAABQAAAnoCvAAAAIwCegK8AAAB4AAxAQIAAAIABQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUGZFZABA6RDpHQNS/2oAWgQAAJYAAAABAAAAAAAABAAAAAPoAAAD6AAAA+gAAAPoAAAD6AAAA+gAAAPoAAAD6AAAA+gAAAPoAAAD6AAAA+gAAAPoAAAAAAACAAAAAwAAABQAAwABAAAAFAAEAEIAAAAGAAQAAQAC6RLpHf//AADpEOkU//8AAAAAAAEABgAKAAAAAQACAAMABQAGAAcACAAJAAoACwAMAA0ABAAAAAAAAAAUACoAZACkAL4A7gEuAVwBcAGEAZ4ByAHyAAAAAQAAAAAD6gMuAAUAAAkBBwkBJwIAAet0/on+iXQDL/4VcwF3/olzAAEAAAAAA+oDLgAFAAATCQEXCQGJAXcBd3T+Ff4VAy/+iQF3c/4VAesAAAAAAwAAAAAEAAQAAAMADwAbAAABITUhBQ4BBy4BJz4BNx4BBRYAFzYANyYAJwYAAQACAP4AAoAE2aOj2QQE2aOj2fyEBgEh2dkBIQYG/t/Z2f7fAcCAQKPZBATZo6PZBATZo9n+3wYGASHZ2QEhBgb+3wAAAAADAAAAAAQABAAACwAXACMAAAEjFTMVMzUzNSM1IwEOAQcuASc+ATceAQUWABc2ADcmACcGAAHAwMCAwMCAAcAE2aOj2QQE2aOj2fyEBgEh2dkBIQYG/t/Z2f7fAkCAwMCAwP8Ao9kEBNmjo9kEBNmj2f7fBgYBIdnZASEGBv7fAAIAAAAAAwAEAAADAAoAADEhNSEBIQkBIREhAwD9AAEA/wABgAGA/wD/AIACAP6AAYABgAACAAAAAANABAAADgAaAAABMh4CFRElBRE0Nz4BMycGFRElBRE0JiMhIgKdCwwHBf7g/uAJBAwKdC8BoAGgX0T+BkQDgAYGCwr9YHZ2AqAOCQQGUS9D/KGrqwNfRlsAAAACAAAAAAP/BAAACwAjAAABDgEHLgEnPgE3HgEFHgEXMjY/ARcVATcBIyc3PgE1LgEnDgECgAOQbW2QAwOQbW2Q/YME2aNGfDIDJAEEYf78MyMCKi4E2aOj2QKAbZADA5BtbZADA5Bto9kELioDJDP+/GEBBCQDMnxGo9kEBNkAAAQAAAAABAAEAAADAAcAFQAZAAABFSE1JRUjNSERMxUhNTMRLgEnIQ4BNyE1IQLA/oACQID9AMACgMABSDf9ADdIvwKA/YABwMDAwICA/sDAwAFAN0gBAUmKwAAAAQAAAAACQAQAAAUAABEBNwkBJwHsU/6HAXpSAmD+YGIBPgE+YgAAAAEAAAAAAkAEAAAFAAARCQEXCQEBev6HUwHs/hMDnv7C/sJiAaABoAABAAAAAAKABAAACwAAERcHFzcXNyc3Jwcn9fVM9PVL9PRL9fQDtfX0TPX1TPT0TPT0AAAABAAAAAAD8APwAAUACwARABcAACEzNTM1IQUzFTMRISUhNSM1IwUjFSERIwJ2fvz+hv2K/H7+hgJ2AXr8fv6G/AF6fvx+fvwBevx+/Px+AXoAAAAAAgAAAAAEAAQAAAMAFgAAAREhEScGFREUFhchPgE1ETQmIyEnIQYDgP0AYh48LQMuLTw8Lf5pa/7ULQMA/gACAN8eLf1YLTwDAzwtAigvPYACAAAAAAASAN4AAQAAAAAAAAABAAAAAQAAAAAAAQAUAAEAAQAAAAAAAgAHABUAAQAAAAAAAwAUABwAAQAAAAAABAAUADAAAQAAAAAABQALAEQAAQAAAAAABgAUAE8AAQAAAAAACgAsAGMAAQAAAAAACwASAI8AAwABBAkAAAACAKEAAwABBAkAAQAoAKMAAwABBAkAAgAOAMsAAwABBAkAAwAoANkAAwABBAkABAAoAQEAAwABBAkABQAWASkAAwABBAkABgAoAT8AAwABBAkACgBYAWcAAwABBAkACwAkAb8gY3VzdG9tLXRvb2xiYXJbMTkwOF1SZWd1bGFyY3VzdG9tLXRvb2xiYXJbMTkwOF1jdXN0b20tdG9vbGJhclsxOTA4XVZlcnNpb24gMS4wY3VzdG9tLXRvb2xiYXJbMTkwOF1Gb250IGdlbmVyYXRlZCB1c2luZyBTeW5jZnVzaW9uIE1ldHJvIFN0dWRpb3d3dy5zeW5jZnVzaW9uLmNvbQAgAGMAdQBzAHQAbwBtAC0AdABvAG8AbABiAGEAcgBbADEAOQAwADgAXQBSAGUAZwB1AGwAYQByAGMAdQBzAHQAbwBtAC0AdABvAG8AbABiAGEAcgBbADEAOQAwADgAXQBjAHUAcwB0AG8AbQAtAHQAbwBvAGwAYgBhAHIAWwAxADkAMAA4AF0AVgBlAHIAcwBpAG8AbgAgADEALgAwAGMAdQBzAHQAbwBtAC0AdABvAG8AbABiAGEAcgBbADEAOQAwADgAXQBGAG8AbgB0ACAAZwBlAG4AZQByAGEAdABlAGQAIAB1AHMAaQBuAGcAIABTAHkAbgBjAGYAdQBzAGkAbwBuACAATQBlAHQAcgBvACAAUwB0AHUAZABpAG8AdwB3AHcALgBzAHkAbgBjAGYAdQBzAGkAbwBuAC4AYwBvAG0AAAAAAgAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAQIBAwEEAQUBBgEHAQgBCQEKAQsBDAENAQ4BDwAIVG9wLWljb24LZG93bi1hcnJvdzIKUFZfWm9vbW91dAlQVl9ab29taW4LUFZfRG93bmxvYWQLUFZfQm9va21hcmsJUFZfU2VhcmNoCFBWX1ByaW50C1BWX1ByZXZpb3VzB1BWX05leHQIUFZfQ2xvc2UMUFZfRml0VG9QYWdlB1BWX09wZW4AAA==) format('truetype');
}

/* custom code end*/

/* style for slider button */

.flex-container {
    display: flex;
    justify-content: flex-end;
}

.render-mode-info {
    background: none;
    border: none;
    padding-left: 0px;
}

.render-mode-info .render-mode-info-icon {
    height: 16px;
    width: 16px;
}

.switchLabel {
    font-family: "Segoe UI", "GeezaPro", "DejaVu Serif", sans-serif;        
    font-weight: 400;
    line-height: 20px;
    letter-spacing: 0.24px;
    text-align: right;
    font-size: 14px;
}

.render-mode-info .render-mode-info-icon::before {
    line-height: 0.5rem;
}

.buttonSwitch {
    Width: 40px;
    Height: 24px;
}

</style>

<script>
import { PdfViewerComponent, Toolbar, Magnification, Navigation, LinkAnnotation, BookmarkView, ThumbnailView, Print, TextSelection, TextSearch } from "@syncfusion/ej2-vue-pdfviewer";
import { ItemDirective, ItemsDirective, ToolbarComponent } from "@syncfusion/ej2-vue-navigations";
import { SwitchComponent } from "@syncfusion/ej2-vue-buttons";

var toolbar;
var viewer;
var fileName;
var currentPageBox;

function updatePageNavigation() {
    if (viewer.currentPageNumber === 1) {
        toolbar.enableItems(document.getElementById('previousPage'), false);
        toolbar.enableItems(document.getElementById('nextPage'), true);
    }
    else if (viewer.currentPageNumber === viewer.pageCount) {
        toolbar.enableItems(document.getElementById('previousPage'), true);
        toolbar.enableItems(document.getElementById('nextPage'), false);
    }
    else {
        toolbar.enableItems(document.getElementById('previousPage'), true);
        toolbar.enableItems(document.getElementById('nextPage'), true);
    }
}

function onCurrentPageBoxKeypress(event) {
    if ((event.which < 48 || event.which > 57) && event.which !== 8 && event.which !== 13) {
        event.preventDefault();
        return false;
    }
    else {
        var currentPageNumber = parseInt(currentPageBox.value);
        if (event.which === 13) {
            if (currentPageNumber > 0 && currentPageNumber <= viewer.pageCount) {
                viewer.navigation.goToPage(currentPageNumber);
            }
            else {
                currentPageBox.value = viewer.currentPageNumber.toString();
            }
        }
        return true;
    }
}

function onCurrentPageBoxClicked() {
    currentPageBox.select();
}

function readFile(args) {
    // tslint:disable-next-line
    let upoadedFiles = args.target.files;
    if (args.target.files[0] !== null) {
        let uploadedFile = upoadedFiles[0];
        fileName = uploadedFile.name;
        if (uploadedFile) {
            let reader = new FileReader();
            reader.readAsDataURL(uploadedFile);
            // tslint:disable-next-line
            reader.onload = function (e) {
                let uploadedFileUrl = e.currentTarget.result;
                viewer.load(uploadedFileUrl, null);
                viewer.fileName = fileName;
            };
        }
    }
};

export default {
    components: {
        'ejs-pdfviewer': PdfViewerComponent,
        'ejs-toolbar': ToolbarComponent,
        'e-items': ItemsDirective,
        'e-item': ItemDirective,
        'ejs-switch': SwitchComponent
    },
    data: function () {
        return {
            documentPath: 'https://cdn.syncfusion.com/content/pdf/hive-succinctly.pdf',
            enableToolbar: false,
            enableNavigationToolbar: false,
        }
    },
    provide: {
        PdfViewer: [Toolbar, Magnification, Navigation, LinkAnnotation, BookmarkView, ThumbnailView, Print, TextSelection, TextSearch]
    },
    methods: {
        openClicked: function (args) {
            document.getElementById('fileUpload').click();
        },
        previousClicked: function (args) {
            viewer.navigation.goToPreviousPage();
        },
        nextClicked: function (args) {
            viewer.navigation.goToNextPage();
        },
        printClicked: function (args) {
            viewer.print.print();
        },
        downloadClicked: function (args) {
            viewer.download();
        },
        pageFitClicked: function (args) {
            viewer.magnification.fitToPage();
        },
        zoomInClicked: function (args) {
            viewer.magnification.zoomIn();
        },
        zoomOutClicked: function (args) {
            viewer.magnification.zoomOut();
        },
        pageChange: function (args) {
            currentPageBox = document.getElementById('currentPage');
            currentPageBox.value = viewer.currentPageNumber.toString();
            updatePageNavigation();
        },
        documentLoad: function (args) {
            viewer = this.$refs.pdfviewer.ej2Instances;
            toolbar = this.$refs.toolbar.ej2Instances;
            currentPageBox = document.getElementById('currentPage');
            currentPageBox.value = '1';
            document.getElementById('totalPage').textContent = 'of ' + viewer.pageCount;
            currentPageBox.addEventListener('keypress', onCurrentPageBoxKeypress);
            currentPageBox.addEventListener('click', onCurrentPageBoxClicked);
            document.getElementById('fileUpload').addEventListener('change', readFile, false);
            updatePageNavigation();
        },
        // Initialize switchObj within the mounted hook
        change: function (args) {
            var viewer = this.$refs.pdfviewer.ej2Instances;
            if (args.checked) {
                viewer.serviceUrl = "";
            } else {
                viewer.serviceUrl = "https://ej2services.syncfusion.com/vue/development/api/pdfviewer";
            }           
            viewer.dataBind();
            viewer.load(viewer.documentPath, null);
        }
    }
};

</script>

// angular/custom-toolbar/src/app.component.ts
import { Component, ViewEncapsulation, OnInit, ViewChild, Inject } from '@angular/core';
import {
    PdfViewerComponent, LinkAnnotationService, BookmarkViewService, MagnificationService,
    ToolbarService, NavigationService, TextSelectionService, PrintService,
    PageChangeEventArgs,
    LoadEventArgs
} from '@syncfusion/ej2-angular-pdfviewer';
import { ToolbarComponent } from '@syncfusion/ej2-angular-navigations';
import { DialogComponent } from '@syncfusion/ej2-angular-popups';
import { ClickEventArgs } from '@syncfusion/ej2-buttons';
import { SwitchComponent } from '@syncfusion/ej2-angular-buttons';

/**
 * Default PdfViewer Controller
 */
@Component({
    selector: 'app-root',
    templateUrl: 'app.component.html',
    encapsulation: ViewEncapsulation.None,
    providers: [LinkAnnotationService, BookmarkViewService, MagnificationService, ToolbarService, NavigationService, TextSelectionService, PrintService],
    styleUrls: ['app.component.css'],
})

export class AppComponent {
    @ViewChild('pdfviewer')
    public pdfviewerControl: PdfViewerComponent;
    @ViewChild('customToolbar')
    public customToolbar: ToolbarComponent;
    @ViewChild('zoomToolbar')
    public zoomToolbar: ToolbarComponent;
    @ViewChild('switch')
    public switch: SwitchComponent;

    public document: string = 'https://cdn.syncfusion.com/content/pdf/hive-succinctly.pdf';
    constructor() {
        
    }
    ngOnInit(): void {
        // ngOnInit function
        document.getElementById('fileUpload').addEventListener('change', this.readFile.bind(this));
    }

    public openDocument(e: ClickEventArgs): void {
        document.getElementById('fileUpload').click();
    }

    public previousClicked(e: ClickEventArgs): void {
        this.pdfviewerControl.navigation.goToPreviousPage();
    }

    public nextClicked(e: ClickEventArgs): void {
        this.pdfviewerControl.navigation.goToNextPage();
    }

    public printClicked(e: ClickEventArgs): void {
        this.pdfviewerControl.print.print();
    }

    public downloadClicked(e: ClickEventArgs): void {
        let fileName: string = (document.getElementById('fileUpload') as HTMLInputElement).value.split('\\').pop();
        if (fileName !== '') {
            this.pdfviewerControl.fileName = fileName;
        }
        this.pdfviewerControl.download();
    }

    public pageFitClicked(e: ClickEventArgs): void {
        this.pdfviewerControl.magnification.fitToPage();
        this.updateZoomButtons();
        this.customToolbar.enableItems(document.getElementById('fitPage'), false);
    }

    public zoomInClicked(e: ClickEventArgs): void {
        this.pdfviewerControl.magnification.zoomIn();
        this.updateZoomButtons();
    }

    public zoomOutClicked(e: ClickEventArgs): void {
        this.pdfviewerControl.magnification.zoomOut();
        this.updateZoomButtons();
    }

    public pageChanged(e: PageChangeEventArgs): void {
        (document.getElementById('currentPage') as HTMLInputElement).value = this.pdfviewerControl.currentPageNumber.toString();
        this.updatePageNavigation();
    }

    public documentLoaded(e: LoadEventArgs): void {
        document.getElementById('totalPage').textContent = 'of ' + this.pdfviewerControl.pageCount;
        (document.getElementById('currentPage') as HTMLInputElement).value = this.pdfviewerControl.currentPageNumber.toString();
        this.updatePageNavigation();
    }

    public onCurrentPageBoxClicked(e: ClickEventArgs): void {
        (document.getElementById('currentPage') as HTMLInputElement).select();
    }

    public onCurrentPageBoxKeypress(e: KeyboardEvent): boolean {
        if ((e.which < 48 || e.which > 57) && e.which !== 8 && e.which !== 13) {
            e.preventDefault();
            return false;
        } else {
            // tslint:disable-next-line:radix
            const currentPageNumber: number = parseInt((document.getElementById('currentPage') as HTMLInputElement).value);
            if (e.which === 13) {
                if (currentPageNumber > 0 && currentPageNumber <= this.pdfviewerControl.pageCount) {
                    this.pdfviewerControl.navigation.goToPage(currentPageNumber);
                } else {
                    // tslint:disable-next-line:max-line-length
                    (document.getElementById('currentPage') as HTMLInputElement).value = this.pdfviewerControl.currentPageNumber.toString();
                }
            }
            return true;
        }
    }

    private updatePageNavigation(): void {
        if (this.pdfviewerControl.currentPageNumber === 1) {
            this.customToolbar.enableItems(document.getElementById('previousPage'), false);
            this.customToolbar.enableItems(document.getElementById('nextPage'), true);
        } else if (this.pdfviewerControl.currentPageNumber === this.pdfviewerControl.pageCount) {
            this.customToolbar.enableItems(document.getElementById('previousPage'), true);
            this.customToolbar.enableItems(document.getElementById('nextPage'), false);
        } else {
            this.customToolbar.enableItems(document.getElementById('previousPage'), true);
            this.customToolbar.enableItems(document.getElementById('nextPage'), true);
        }
    }

    private updateZoomButtons(): void {
        if (this.pdfviewerControl.zoomPercentage <= 50) {
            this.zoomToolbar.enableItems(document.getElementById('zoomIn'), true);
            this.zoomToolbar.enableItems(document.getElementById('zoomOut'), false);
            this.zoomToolbar.enableItems(document.getElementById('fitPage'), true);
        } else if (this.pdfviewerControl.zoomPercentage >= 400) {
            this.zoomToolbar.enableItems(document.getElementById('zoomIn'), false);
            this.zoomToolbar.enableItems(document.getElementById('zoomOut'), true);
            this.zoomToolbar.enableItems(document.getElementById('fitPage'), true);
        } else {
            this.zoomToolbar.enableItems(document.getElementById('zoomIn'), true);
            this.zoomToolbar.enableItems(document.getElementById('zoomOut'), true);
            this.zoomToolbar.enableItems(document.getElementById('fitPage'), true);
        }
    }

    // tslint:disable-next-line
    private readFile(args: any): void {
        // tslint:disable-next-line
        let upoadedFiles: any = args.target.files;
        if (args.target.files[0] !== null) {
            let uploadedFile: File = upoadedFiles[0];
            if (uploadedFile) {
                let reader: FileReader = new FileReader();
                reader.readAsDataURL(uploadedFile);
                // tslint:disable-next-line
                let proxy: any = this;
                // tslint:disable-next-line
                reader.onload = (e: any): void => {
                    let uploadedFileUrl: string = e.currentTarget.result;
                    proxy.pdfviewerControl.load(uploadedFileUrl, null);
                };
            }
        }
    }
    public change(e: any): void {
        if (e.checked) {
            this.pdfviewerControl.serviceUrl = '';
        }
        else {
            this.pdfviewerControl.serviceUrl = 'https://ej2services.syncfusion.com/angular/development/api/pdfviewer';
        }
        this.pdfviewerControl.dataBind();
        this.pdfviewerControl.load(this.pdfviewerControl.documentPath, null);
    }
}

<div class='control-section'>
    <div class="flex-container">
        <label class="switchLabel" for="checked">Standalone PDF Viewer</label>
        <div class="e-message render-mode-info">
            <span class="e-msg-icon render-mode-info-icon" title="Turn OFF to render the PDF Viewer as server-backed"></span>
        </div>
        <div>
            <ejs-switch cssClass="buttonSwitch" id="checked" (change)="change($event)" [checked]="true"></ejs-switch>
        </div>
    </div>
    <div class='content-wrapper e-tbar-section'>
        <div class='e-sample-resize-container'>
            <ejs-toolbar id='topToolbar' #customToolbar>
                <e-items>
                    <e-item prefixIcon='e-pv-open-document-icon' id='openDocument' tooltipText='Open' (click)='openDocument($event)'>
                    </e-item>
                    <e-item prefixIcon='e-pv-previous-page-navigation-icon' id='previousPage' tooltipText='Previous Page' (click)='previousClicked($event)'
                        align='Center'></e-item>
                    <e-item prefixIcon='e-pv-next-page-navigation-icon' id='nextPage' tooltipText='Next Page' (click)='nextClicked($event)' align='Center'></e-item>
                    <e-item align='Center'>
                        <ng-template #template>
                            <div class=''><input type='text' class='e-input-group e-pv-current-page-number' id='currentPage' value="0"
                                    (keypress)='onCurrentPageBoxKeypress($event)' (click)='onCurrentPageBoxClicked($event)' /></div>
                            <div style='margin-left: 6px'><span class='e-pv-total-page-number' id='totalPage'>of 0</span></div>
                        </ng-template>
                    </e-item>
                    <e-item prefixIcon='e-pv-print-document-icon' tooltipText='Print' (click)='printClicked($event)' align='Right'></e-item>
                    <e-item prefixIcon='e-pv-download-document-icon' tooltipText='Download' (click)='downloadClicked($event)' align='Right'></e-item>
                </e-items>
            </ejs-toolbar>
        </div>
        <ejs-toolbar id='magnificationToolbar' #zoomToolbar>
            <e-items>
                <e-item prefixIcon='e-pv-fit-page-icon' id='fitPage' tooltipText='Fit to page' (click)='pageFitClicked($event)'></e-item>
                <e-item prefixIcon='e-pv-zoom-in-icon' id='zoomIn' tooltipText='Zoom in' (click)='zoomInClicked($event)'></e-item>
                <e-item prefixIcon='e-pv-zoom-out-sample' id='zoomOut' tooltipText='Zoom out' (click)='zoomOutClicked($event)'></e-item>
            </e-items>
        </ejs-toolbar>
        <ejs-pdfviewer #pdfviewer id='pdfViewer' [documentPath]='document' [enableToolbar]=false [enableNavigationToolbar]=false (pageChange)='pageChanged($event)'
            (documentLoad)='documentLoaded($event)'  style="height:640px; display: block">
        </ejs-pdfviewer>
        <input type="file" id="fileUpload" accept=".pdf" style="display:block;visibility:hidden;width:0;height:0;">
    </div>
</div>
